### ISSUE TITLE
Domain Driven Design mit Relationalen Datenbanken (Jens Schauder)

### ISSUE THREAD

**Issue by schauder** [cyberjug/meetup#5]
Domain Driven Design (DDD) führt die Konzepte Aggregate, Aggregateroot und Repository ein.
Wenn man diese Konzepte ernst nimmt stellt man fest, dass viele Dinge, die man sich <strikethrough>im Kampf</strikethrough> in der Arbeit mit JPA angewöhnt hat nicht wirklich akzeptabel sind.
Mehr noch, es werden sogar ganze Features von JPA überflüssig oder zumindest wesentlich weniger wichtig.

In diesem Vortrag stelle ich vor welche Auswirkungen DDD auf ein Objekt Modell hat,
 und wie dies massiv die Komplexität reduziert.
 Wir werden sehen, wie es Integrationstests vereinfacht und ganze Kategorien von Fehlern vermeidet, die aktuell in sehr vielen Datenbankanwendungen vorhanden sind.

Diese Designentscheidungen eröffnen schließlich auch noch die Möglichkeit über die Vor- und Nachteile von Foreignkeys nach zu denken um diese gezielter und bewusster einsetzen zu können.

Das beschriebene Vorgehen ist integraler Bestandteil der Architektur von Spring Data JDBC und in den letzten ca 10 Minuten werden wir dies nutzen um uns das Ganze in der Praxis anzuschauen.

**Comment by HaraldWalker** [comment]
unterscheidet sich das von deinem Vortrag
Domain-Driven Design with Relational Databases Using Spring Data JDBC
https://www.youtube.com/watch?v=GOSW911Ox6s ?

**Comment by schauder** [comment]
Nein, ist der gleiche Vortrag. Nur der Abstract und der Titel wurden ein wenig für gewisse Konferenzen optimiert.

**Comment by feststelltaste** [comment]
done
