### ISSUE TITLE
Auswahl einer Video/Conferencing Lösung

### ISSUE THREAD

**Issue by schauder** [cyberjug/meetup#6]
Anforderungen/Kriterien bisher:

* Preis
* Recording Möglichkeit.
* Teilnehmerzahl ausreichend (Wieviele brauchen wir?)
* Maximale Dauer ausreichend (2h müssten reichen, oder?)

**Comment by atomfrede** [comment]
Es sieht so aus, als ob Jitsi als OSS auch live streaming nach youtube kann (allerdings noch nicht ausprobiert). Als normale Videokonferenz ist es sehr gut und funktioniert ohne plugins etc. https://jitsi.org/live-streaming-and-recording-a-jitsi-conference/

**Comment by timmhirsens** [comment]
Man könnte natürlich statt conferencing auch eine der Streaming Plattformen (twitch oder YouTube) nehmen. Erfordert aber etwas mehr know how beim Vortragenden.

**Comment by feststelltaste** [comment]
Ich denke für die ersten 2-3 Meetups würde eine 08/15-Live-Streaming-Plattform taugen. Das verwendet z. B. das Neo4j Online-Meetup. Aber Aufwand für das Einrichten ist leider notwendig. Später sollten wir schon versuchen, es den SprecherInnen möglichst einfach zu machen.

**Comment by meistermeier** [comment]
Also ich habe unverbindlich bei uns (Neo4j) angefragt, ob ein Sponsoring unserer BigMarker Lösung möglich wäre: Ja. Wir hatten das bei unserer letzten Online Konferenz genutzt.
Falls Interesse besteht, kann ich das gerne in Angriff nehmen.

**Comment by feststelltaste** [comment]
Konnte auch gerade noch mit der Orga von https://virtualddd.com/ geredet. Sie nehmen zoom.us mit einem Add-On, wo 100 Personen teilnehmen (d. h. "Hände heben" oder direkt mitchatten können), aber 10000 parallel auf YouTube mitschauen können. Würde auch gehen als weitere Möglichkeit.

**Comment by meistermeier** [comment]
Wir haben aktuell den Elite plan bei BigMarker. https://www.bigmarker.com/pricing
Damit wäre auch ein YT Streaming möglich. Da würde sogar der Plus plan ausreichen, aber das kann man ja noch besprechen.

**Comment by HaraldWalker** [comment]
Jitsi features:
- no software installation necessary (depends on browser)
- Recording
- Streaming a conference to YouTube live (beta)
- Screen sharing
- Chat
- Shared documents (Etherpad)
- Raise/lower hand
- Android/iOS apps
- Slack integration (https://jitsi.org/slack/)

100% free, open source

Sieht eigentlich ganz gut aus. Konnte nichts zu einem Limit finden. Bei der Slack Integration stand etwas von bis zu 50 Personen (und der Rest müsste dann via YouTube Live passiv zuschauen).

**Comment by feststelltaste** [comment]
YouTube-Live-Streaming möchte ich am besten vermeiden, da ich keine Rundfunklizenz beantragen möchte.

**Comment by schauder** [comment]
Unter welchen Bedingungen brauch man den ein Rundfunklizenz?

Selbst googelt der Mensch:

> * linear, also live verbreitet werden,
> * von mehr als 500 Zuschauern/Usern gleichzeitig gesehen werden können,
> * redaktionell gestaltet sind und
> * „entlang eines Sendeplans“ regelmäßig und wiederholt verbreitet werden.

https://www.medienanstalt-nrw.de/regulierung/internet/rundfunklizenzen-fuer-live-streaming-angebote.html

**Comment by feststelltaste** [comment]
Jitsi scheint nicht gut zu skalieren (https://community.jitsi.org/t/some-questions-about-jitsi-meet-features/14689). Mit BigMarker bin ich derzeit höchstzufrieden. Daher schließe ich das Ticket vorerst.

**Comment by feststelltaste** [comment]
(nachdem ich mir hierfür Rechte eingeräumt habe 🤦🏻‍♂️ )
