### ISSUE TITLE
Modernisierung von legacy Web-Apps mit Polyfills am Beispiel des Blink-Tags (Ralf D. Müller)

### ISSUE THREAD

**Issue by rdmueller** [cyberjug/meetup#9]
## Abstract

Wer kennt das nicht? Die neuste Version des AOL-Browsers wird veröffentlicht und das <blink>-Tag, welches man erst im letzten Spring mit Mühe in die eigene fast-cgi Web-App eingebaut hat, wird nicht mehr unterstützt.
In diesem Vortrag zeige ich, wie Ihr verhindert, dass Eure Web-Anwendung durch Updates zu einer Legacy-Anwendung wird. Die verwendete Technology "Polyfill" sorgt dafür, dass sich auch neuere Browser noch an den original HTML-Standard halten.
Ein Wermutstropfen bleibt leider, denn auch mit Polyfill funktioniert der <blink>-Tag leider nicht mehr in aktuellen Versionen des Lynx-Browsers.

## Art des Vortrags

Lightning-Talk, 10 Minuten. Gerne kann ich das Thema auch zum Workshop ausarbeiten.

**Comment by feststelltaste** [comment]
Also ich interessiere mich für einen Vortragenden oder Vortragende, die sowas machen könnten wie "Programmierem wie damals" (zu den Anfangszeiten von Java in den 90ern), um mal wieder etwas Respekt von der Entwicklung von Java zu vermitteln :-D . Bist Du dafür auch zu haben?

**Comment by rdmueller** [comment]
LOL. Ja, würde sicher Spass machen. Bräuchte ich aber einiges an Vorbereitung.

**Comment by feststelltaste** [comment]
Ich frage mal im Slack-Channel

**Comment by feststelltaste** [comment]
Ich mache das mal zu, da die Diskussion in Slack weitergeht. Wer jemanden kennt, bitte gerne melden!
